### ISSUE TITLE
ICON_LES is broken

### ISSUE THREAD

**Issue by d70-t** [eurec4a/how_to_eurec4a#102]
The [ICON_LES page](https://howto.eurec4a.eu/icon_les.html) is currently (and since a while) broken. This was useful for testing #101 but should be fixed.

My initial investigation showed that the [EUREC4A_ICON-LES_control_DOM03_reff_native.zarr](https://swiftbrowser.dkrz.de/public/dkrz_948e7d4bbfbb445fbff5315fc433e36a/EUREC4A_LES/experiment_2/EUREC4A_ICON-LES_control_DOM03_reff_native.zarr/) dataset seems to be corrupted. While `.zmetadata` shows there *should* be a `time` variable, there is none. For some reason, this doesn't get picked up correctly by the client library as an error, and instead some bytes of the error response seem to be interpreted as time values. These (garbage) values don't fit into a human time range, and thus are decoded as CFtime objects instead of `np.datetime64`, which in turn crashes `matplotlib`.

Possible fixes for the notebook:
* [x] fix the dataset by (re-) uploading the `time` variable
* [ ] throw the (likely unusable) dataset out of the `eurec4a_intake` catalog
* [ ] some code in the notebook which catches the situation and keeps it running for the other datasets

@observingClouds any thoughts?

**Comment by observingClouds** [comment]
Thanks @d70-t for determine the root problem of this. I just uploaded the time variable. It should be fixed now.

**Comment by d70-t** [comment]
Thanks for the quick fix! It works now (as demonstrated by #101).
