### ISSUE TITLE
Cache updates

### ISSUE THREAD

**Issue by d70-t** [eurec4a/how_to_eurec4a#104]
While the caching already helps a lot reducing the build time, there is still an issue with flaky notebooks:

If a cache entry (with a given key) exists, it is restored. Afterwards all the previously failed and newly added or modified notebooks are executed. When finished, there will ideally be more successfully executed notebooks in the cache, thus the cache probably should get updated. Currently this does not happen (as the save cache action refuses to write a cache entry which already exists). There are probably two ways out:

* [purge cache](https://github.com/marketplace/actions/purge-cache) before saving
* find a clever way to use [restore keys](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#matching-a-cache-key) or something similar, to create new cache entries which are preferred during restore over older entries and let github's cache eviction logic take care of older entries

**Comment by observingClouds** [comment]
Great! I saw this error messages in the previous PR checks.
