### ISSUE TITLE
add Marek's HAMP LWP data

### ISSUE THREAD

**Issue by tmieslinger** [eurec4a/how_to_eurec4a#19]
https://observations.ipsl.fr/aeris/eurec4a-data/AIRCRAFT/HALO/HAMP/LWP_IWV_v0.8/

**Comment by d70-t** [comment]
There are [HAMP IVW and LWP datasets shown in the book](https://howto.eurec4a.eu/hamp_comparison.html#plot-timeseries). Thus I'd consider this issue as solved.
