### ISSUE TITLE
make a chapter on HAMP cloud mask?

### ISSUE THREAD

**Issue by tmieslinger** [eurec4a/how_to_eurec4a#26]
separate chapter on calculating the HAMP cloud mask using Mareks functions and plotting the data according to his [example](https://github.com/MeraX/HAMP-cloud-mask/blob/master/plot_hamp_wales_cloudmasks.py).

Maybe combine it with [issue#19](https://github.com/tmieslinger/how_to_eurec4a/issues/19)?

**Comment by MeraX** [comment]
It would be even better to use this code:

https://github.com/MeraX/HAMP-cloud-mask/blob/master/plot_hamp_wales_specmacs.py

It creates this plot:
![Example plot](https://atmos.meteo.uni-koeln.de/~mjacob/HAMP-cloud-mask_example.png)

I would need a little help to change all data sources from local files to intake links.
