### ISSUE TITLE
Compiled book is not visible to outsiders

### ISSUE THREAD

**Issue by RobertPincus** [eurec4a/how_to_eurec4a#30]
Hi @tmieslinger I'm delighted that this book is now part of the EUREC4A organization. Can you check that the compiled book on Gitlab pages is visible to all? I just tried to follow the link to the book, I was asked to authorize at GWDG, and when I did the page is not found. Many people won't have GWDG address.

**Comment by d70-t** [comment]
Sorry, this was my error. I've changed the permissions.

**Comment by d70-t** [comment]
For reference, the URL to the book has been changed as well. If you access the old URL, you'll experience exactly the same error.

The new URL is https://eurec4a.pages.gwdg.de/how_to_eurec4a/
There's also a Handle-URL. I am not yet convinced that this is a good idea, but I thought we can try it: http://doi.org/21.11101/0000-0007-EBF5-C it should point to the same page and can be updated to point to something else.
